#!/bin/bash

input=$1
container=/scratch/m/mchakrav/afajardo/containers/afni.sif

[ ! -f $container ] && echo "Container doesn't exist." && exit 1

command="singularity exec -B /scratch:/misc $container $input"

eval $command



